Add setup
BasitKorede/my-personal-portfolio pull request #1
Opened 2021-10-04 12:23 UTC by BasitKorede

# SETUP FOR PORTFOLIO PROJECT.

### This pull request adds the following.
- It consist of the `Nav-bar` (navigation bar).
- The about me section.
- The language,skill and framework section.
- And various social media platform i can be contacted.

2021-10-04 23:08 UTC, adejam requested changes
Milestone seems to be done with just a few exception. Please let's make changes to the reviews below.

2021-10-04 23:08 UTC, adejam commented on css/index.css
> +@import "./screens/large-screen.css" screen and (min-width: 481px);
We should not have an import to an empty path

2021-10-04 23:08 UTC, adejam commented on index.html
> +          <a> Basit Korede </a>
This anchor tag has no href attribute. All `<a>` tags should have an HTML attribute. If we don't want to have an empty href then we can use `href="#"` instead

2021-10-04 23:08 UTC, adejam commented on index.html
> +      </nav>
Only the hamburger button should have the nav tag. And not all the links/elements in the header

2021-10-04 23:08 UTC, adejam commented on index.html
> +          <a> Basit Korede </a>
This should have a font size of 18px as described in the design

2021-10-04 23:08 UTC, adejam commented on index.html
> +      <h1 class="name-header">Basit Korede</h1>
This header should be in the `section`

2021-10-04 23:08 UTC, adejam commented on index.html
> +            /></a>
All decorations should always be background images and not <img /> tags. Please refer to this [article](https://www.w3docs.com/snippets/html/when-to-use-html-img-tag-and-css-background-image-property.html) for more on this. Let us fix this in every other case

2021-10-05 10:05 UTC, BasitKorede commented on css/index.css
> +@import "./screens/large-screen.css" screen and (min-width: 481px);
That for calling this out, i will make the advice change(s).

2021-10-05 10:09 UTC, BasitKorede commented on index.html
> +          <a> Basit Korede </a>
Thanks to you awareness i will make the advice change(s).

2021-10-05 10:11 UTC, BasitKorede commented on index.html
> +      </nav>
thanks for pointing this out, it so bad to have made this type of mistake. I will make the due change(s).

2021-10-05 10:55 UTC, adejam approved these changes
Looks good to me. We should merge this PR and move to the next milestone.

2021-10-05 10:58 UTC, merged