Add mobile version
BasitKorede/my-personal-portfolio pull request #2
Opened 2021-10-06 13:20 UTC by BasitKorede

#  MOBILE VERSION MY PErFOR PORTFOLIO PROJECT.

### This pull request adds the following.
- My recent work section.
  -  by my recent work header in h2 header.
  -  my recent work div which has the display of Grid.
   - my recent work image div. 
   - my recent work header in h3 header .
   - my recent work multiple post story (story about each project).
   - languages used while developing the projects and has the property of display flex.
   - the see project button which is assigned pseudo classes of `hover` `active` and `disabled`.

2021-10-07 05:41 UTC, adejam requested changes
### Looks good, though the works section would definitely need a revamp in a way.

Let's make changes to the review

2021-10-07 05:41 UTC, adejam commented on index.html
> +      <section class="my-recent-work">
this section or maybe another parent `div` should have the display `grid` that houses all works section. while each works container should then use a display `flex` to organize its children elements

2021-10-07 05:41 UTC, adejam commented on index.html
> +            <button
<img width="388" alt="Screenshot 2021-10-07 at 06 35 32" src="https://user-images.githubusercontent.com/53398818/136325922-82432a00-0b77-407d-93bf-8001549b03e4.png">
The buttons should have the active, hover and pressed states

2021-10-11 18:57 UTC, BasitKorede commented on index.html
> +            <button
thanks, I will make the changes now.

2021-10-11 18:57 UTC, merged